# Generated by Django 3.2.6 on 2021-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BITS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Spotify_Embeded_Code',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='Spotify_Embeded_Code',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
