# Generated by Django 3.2.6 on 2021-09-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BITS', '0002_auto_20210910_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='description',
            new_name='lryics',
        ),
    ]
